spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://47.100.97.46:3306/mall?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  rabbitmq:
    host: 47.100.97.46
    username: admin
    password: admin
    port: 5672
    virtual-host: my_vhost
server:
  port: 7011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/