spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://47.100.97.46:3306/mall?serverTimezone=GMT%2B8&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  rabbitmq:
    host: 47.100.97.46
    username: admin
    password: admin
    port: 5672
    virtual-host: my_vhost
  redis:
    host: 47.100.97.46
    port: 6379
  main:
    allow-bean-definition-overriding: true
server:
  port: 7012
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/